services:
  backend:
    platform: linux/amd64
    image: chl11wq12/young-buddha-backend:v0.1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: young-buddha-backend
    env_file:
      - backend/.env
    volumes:
      - backend-data:/app/data
    ports:
      - "8080:8080"

  frontend:
    platform: linux/amd64
    image: chl11wq12/young-buddha-frontend:v0.1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_ORIGIN: http://backend:8080
    container_name: young-buddha-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NEXT_PUBLIC_USE_MOCK_AUTH=false
    env_file:
      - frontend/.env.local
    ports:
      - "3000:3000"

volumes:
  backend-data:
    driver: local
